//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionSource) DeepCopyInto(out *CustomResourceDefinitionSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionSource.
func (in *CustomResourceDefinitionSource) DeepCopy() *CustomResourceDefinitionSource {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceDefinitionSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionSourceList) DeepCopyInto(out *CustomResourceDefinitionSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomResourceDefinitionSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionSourceList.
func (in *CustomResourceDefinitionSourceList) DeepCopy() *CustomResourceDefinitionSourceList {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceDefinitionSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionSourceSpec) DeepCopyInto(out *CustomResourceDefinitionSourceSpec) {
	*out = *in
	out.Reference = in.Reference
	in.CRDNames.DeepCopyInto(&out.CRDNames)
	out.VersionDiscovery = in.VersionDiscovery
	if in.Provides != nil {
		in, out := &in.Provides, &out.Provides
		*out = make([]DependencyReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manages != nil {
		in, out := &in.Manages, &out.Manages
		*out = make([]DependencyReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]DependencyReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionSourceSpec.
func (in *CustomResourceDefinitionSourceSpec) DeepCopy() *CustomResourceDefinitionSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionSourceStatus) DeepCopyInto(out *CustomResourceDefinitionSourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionSourceStatus.
func (in *CustomResourceDefinitionSourceStatus) DeepCopy() *CustomResourceDefinitionSourceStatus {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroup) DeepCopyInto(out *DependencyGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroup.
func (in *DependencyGroup) DeepCopy() *DependencyGroup {
	if in == nil {
		return nil
	}
	out := new(DependencyGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroupCRD) DeepCopyInto(out *DependencyGroupCRD) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroupCRD.
func (in *DependencyGroupCRD) DeepCopy() *DependencyGroupCRD {
	if in == nil {
		return nil
	}
	out := new(DependencyGroupCRD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroupList) DeepCopyInto(out *DependencyGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DependencyGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroupList.
func (in *DependencyGroupList) DeepCopy() *DependencyGroupList {
	if in == nil {
		return nil
	}
	out := new(DependencyGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroupReference) DeepCopyInto(out *DependencyGroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroupReference.
func (in *DependencyGroupReference) DeepCopy() *DependencyGroupReference {
	if in == nil {
		return nil
	}
	out := new(DependencyGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroupSpec) DeepCopyInto(out *DependencyGroupSpec) {
	*out = *in
	if in.CRDs != nil {
		in, out := &in.CRDs, &out.CRDs
		*out = make([]DependencyGroupCRD, len(*in))
		copy(*out, *in)
	}
	if in.HarnessRef != nil {
		in, out := &in.HarnessRef, &out.HarnessRef
		*out = new(HarnessReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroupSpec.
func (in *DependencyGroupSpec) DeepCopy() *DependencyGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DependencyGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGroupStatus) DeepCopyInto(out *DependencyGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGroupStatus.
func (in *DependencyGroupStatus) DeepCopy() *DependencyGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DependencyGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyReference) DeepCopyInto(out *DependencyReference) {
	*out = *in
	if in.DependencyGroup != nil {
		in, out := &in.DependencyGroup, &out.DependencyGroup
		*out = new(DependencyGroupReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyReference.
func (in *DependencyReference) DeepCopy() *DependencyReference {
	if in == nil {
		return nil
	}
	out := new(DependencyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryReference) DeepCopyInto(out *DiscoveryReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryReference.
func (in *DiscoveryReference) DeepCopy() *DiscoveryReference {
	if in == nil {
		return nil
	}
	out := new(DiscoveryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessReference) DeepCopyInto(out *HarnessReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessReference.
func (in *HarnessReference) DeepCopy() *HarnessReference {
	if in == nil {
		return nil
	}
	out := new(HarnessReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRevision) DeepCopyInto(out *InstanceRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRevision.
func (in *InstanceRevision) DeepCopy() *InstanceRevision {
	if in == nil {
		return nil
	}
	out := new(InstanceRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRevisionList) DeepCopyInto(out *InstanceRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRevisionList.
func (in *InstanceRevisionList) DeepCopy() *InstanceRevisionList {
	if in == nil {
		return nil
	}
	out := new(InstanceRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRevisionSpec) DeepCopyInto(out *InstanceRevisionSpec) {
	*out = *in
	in.Values.DeepCopyInto(&out.Values)
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRevisionSpec.
func (in *InstanceRevisionSpec) DeepCopy() *InstanceRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRevisionStatus) DeepCopyInto(out *InstanceRevisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRevisionStatus.
func (in *InstanceRevisionStatus) DeepCopy() *InstanceRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorHarness) DeepCopyInto(out *OperatorHarness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorHarness.
func (in *OperatorHarness) DeepCopy() *OperatorHarness {
	if in == nil {
		return nil
	}
	out := new(OperatorHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorHarness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorHarnessList) DeepCopyInto(out *OperatorHarnessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorHarness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorHarnessList.
func (in *OperatorHarnessList) DeepCopy() *OperatorHarnessList {
	if in == nil {
		return nil
	}
	out := new(OperatorHarnessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorHarnessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorHarnessOperator) DeepCopyInto(out *OperatorHarnessOperator) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorHarnessOperator.
func (in *OperatorHarnessOperator) DeepCopy() *OperatorHarnessOperator {
	if in == nil {
		return nil
	}
	out := new(OperatorHarnessOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorHarnessSpec) DeepCopyInto(out *OperatorHarnessSpec) {
	*out = *in
	in.Operator.DeepCopyInto(&out.Operator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorHarnessSpec.
func (in *OperatorHarnessSpec) DeepCopy() *OperatorHarnessSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorHarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorHarnessStatus) DeepCopyInto(out *OperatorHarnessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorHarnessStatus.
func (in *OperatorHarnessStatus) DeepCopy() *OperatorHarnessStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorHarnessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceReference) DeepCopyInto(out *SourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceReference.
func (in *SourceReference) DeepCopy() *SourceReference {
	if in == nil {
		return nil
	}
	out := new(SourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionDiscovery) DeepCopyInto(out *VersionDiscovery) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionDiscovery.
func (in *VersionDiscovery) DeepCopy() *VersionDiscovery {
	if in == nil {
		return nil
	}
	out := new(VersionDiscovery)
	in.DeepCopyInto(out)
	return out
}
