---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo-v6
spec:
  interval: 5m
  provider: generic
  ref:
    semver: 6.x
  url: oci://ghcr.io/stefanprodan/charts/podinfo
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: podinfo
spec:
  exclusionList:
  - ^.*\.sig$
  - ^sha256-.+$
  image: ghcr.io/stefanprodan/charts/podinfo
  interval: 5m
  provider: generic
---
apiVersion: helmetica.io/v1
kind: CustomResourceDefinitionSource
metadata:
  labels:
    app.kubernetes.io/name: chrysopoeia
    app.kubernetes.io/managed-by: kustomize
  name: podinfo-v6
spec:
  reference:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    name: podinfo-v6
  versionDiscovery:
    reference:
      apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: podinfo
