// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// CustomResourceDefinitionSourceSpecApplyConfiguration represents a declarative configuration of the CustomResourceDefinitionSourceSpec type for use
// with apply.
//
// CustomResourceDefinitionSourceSpec defines the desired state of CustomResourceDefinitionSource.
type CustomResourceDefinitionSourceSpecApplyConfiguration struct {
	// Reference is a reference to the source of the bundle.
	Reference *SourceReferenceApplyConfiguration `json:"reference,omitempty"`
	// CRDNames is the `.spec.names` field of the generated [apiextv1.CustomResourceDefinition].
	// If not set takes the name from the chart's metadata or falls back to the default `Instance` kind.
	// Please note that changing this field generates a new CRD and does not update the existing one.
	// The old CRD will be left in the cluster and must be removed manually.
	CRDNames *apiextensionsv1.CustomResourceDefinitionNames `json:"crdNames,omitempty"`
	// VersionDiscovery defines how to discover the version of the source.
	VersionDiscovery *VersionDiscoveryApplyConfiguration `json:"versionDiscovery,omitempty"`
	// Provides lists the DependencyGroups whose CRDs the chart of this source ships. It grants the
	// chart write access to those CRDs and lets Helm install them; it says nothing about who operates
	// them, that is Manages. Exactly one source may provide a group, otherwise two charts install the
	// same CRDs over each other. An operator that bundles its CRDs provides and manages the group,
	// while an operator whose CRDs come in a chart of their own only manages it.
	Provides []DependencyReferenceApplyConfiguration `json:"provides,omitempty"`
	// Manages declares that this source deploys the operator managing the CRDs of a DependencyGroup.
	// The instance of a managing source is the provider consumers are wired to: it is harnessed to the
	// group's scope and granted access to the namespaces that require the group.
	// A single group can be managed: the harness proxy scopes a cluster-scoped list to one label, and
	// a label selector cannot express "carries either label".
	Manages []DependencyReferenceApplyConfiguration `json:"manages,omitempty"`
	// Requires lists the DependencyGroups that instances of this source consume.
	Requires []DependencyReferenceApplyConfiguration `json:"requires,omitempty"`
}

// CustomResourceDefinitionSourceSpecApplyConfiguration constructs a declarative configuration of the CustomResourceDefinitionSourceSpec type for use with
// apply.
func CustomResourceDefinitionSourceSpec() *CustomResourceDefinitionSourceSpecApplyConfiguration {
	return &CustomResourceDefinitionSourceSpecApplyConfiguration{}
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithReference(value *SourceReferenceApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.Reference = value
	return b
}

// WithCRDNames sets the CRDNames field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRDNames field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithCRDNames(value apiextensionsv1.CustomResourceDefinitionNames) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.CRDNames = &value
	return b
}

// WithVersionDiscovery sets the VersionDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VersionDiscovery field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithVersionDiscovery(value *VersionDiscoveryApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.VersionDiscovery = value
	return b
}

// WithProvides adds the given value to the Provides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Provides field.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithProvides(values ...*DependencyReferenceApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProvides")
		}
		b.Provides = append(b.Provides, *values[i])
	}
	return b
}

// WithManages adds the given value to the Manages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Manages field.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithManages(values ...*DependencyReferenceApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithManages")
		}
		b.Manages = append(b.Manages, *values[i])
	}
	return b
}

// WithRequires adds the given value to the Requires field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Requires field.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithRequires(values ...*DependencyReferenceApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRequires")
		}
		b.Requires = append(b.Requires, *values[i])
	}
	return b
}
