// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CustomResourceDefinitionSourceStatusApplyConfiguration represents a declarative configuration of the CustomResourceDefinitionSourceStatus type for use
// with apply.
//
// CustomResourceDefinitionSourceStatus defines the observed state of CustomResourceDefinitionSource
type CustomResourceDefinitionSourceStatusApplyConfiguration struct {
	// Conditions holds the conditions for the CustomResourceDefinitionSource.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// AppliedReferenceGeneration is the last applied generation of the referenced source.
	AppliedReferenceGeneration *int64 `json:"appliedReferenceGeneration,omitempty"`
	// AppliedReferenceRevision is the last applied revision of the referenced source.
	AppliedReferenceRevision *string `json:"appliedReferenceRevision,omitempty"`
}

// CustomResourceDefinitionSourceStatusApplyConfiguration constructs a declarative configuration of the CustomResourceDefinitionSourceStatus type for use with
// apply.
func CustomResourceDefinitionSourceStatus() *CustomResourceDefinitionSourceStatusApplyConfiguration {
	return &CustomResourceDefinitionSourceStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CustomResourceDefinitionSourceStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *CustomResourceDefinitionSourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAppliedReferenceGeneration sets the AppliedReferenceGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliedReferenceGeneration field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceStatusApplyConfiguration) WithAppliedReferenceGeneration(value int64) *CustomResourceDefinitionSourceStatusApplyConfiguration {
	b.AppliedReferenceGeneration = &value
	return b
}

// WithAppliedReferenceRevision sets the AppliedReferenceRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliedReferenceRevision field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceStatusApplyConfiguration) WithAppliedReferenceRevision(value string) *CustomResourceDefinitionSourceStatusApplyConfiguration {
	b.AppliedReferenceRevision = &value
	return b
}
