// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// CustomResourceDefinitionSourceSpecApplyConfiguration represents a declarative configuration of the CustomResourceDefinitionSourceSpec type for use
// with apply.
//
// CustomResourceDefinitionSourceSpec defines the desired state of CustomResourceDefinitionSource.
type CustomResourceDefinitionSourceSpecApplyConfiguration struct {
	// Reference is a reference to the source of the bundle.
	Reference *SourceReferenceApplyConfiguration `json:"reference,omitempty"`
	// CRDNames is the `.spec.names` field of the generated [apiextv1.CustomResourceDefinition].
	// If not set takes the name from the chart's metadata or falls back to the default `Instance` kind.
	// Please note that changing this field generates a new CRD and does not update the existing one.
	// The old CRD will be left in the cluster and must be removed manually.
	CRDNames *apiextensionsv1.CustomResourceDefinitionNames `json:"crdNames,omitempty"`
	// VersionDiscovery defines how to discover the version of the source.
	VersionDiscovery *VersionDiscoveryApplyConfiguration `json:"versionDiscovery,omitempty"`
}

// CustomResourceDefinitionSourceSpecApplyConfiguration constructs a declarative configuration of the CustomResourceDefinitionSourceSpec type for use with
// apply.
func CustomResourceDefinitionSourceSpec() *CustomResourceDefinitionSourceSpecApplyConfiguration {
	return &CustomResourceDefinitionSourceSpecApplyConfiguration{}
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithReference(value *SourceReferenceApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.Reference = value
	return b
}

// WithCRDNames sets the CRDNames field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRDNames field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithCRDNames(value apiextensionsv1.CustomResourceDefinitionNames) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.CRDNames = &value
	return b
}

// WithVersionDiscovery sets the VersionDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VersionDiscovery field is set to the value of the last call.
func (b *CustomResourceDefinitionSourceSpecApplyConfiguration) WithVersionDiscovery(value *VersionDiscoveryApplyConfiguration) *CustomResourceDefinitionSourceSpecApplyConfiguration {
	b.VersionDiscovery = value
	return b
}
