// Code generated by controller-gen. DO NOT EDIT.

package v1

// DependencyApplyConfiguration represents a declarative configuration of the Dependency type for use
// with apply.
type DependencyApplyConfiguration struct {
	// Name of the dependency.
	// Should be the fully qualified crd name as written in the .metadata.name field of the CRD.
	Name *string `json:"name,omitempty"`
}

// DependencyApplyConfiguration constructs a declarative configuration of the Dependency type for use with
// apply.
func Dependency() *DependencyApplyConfiguration {
	return &DependencyApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DependencyApplyConfiguration) WithName(value string) *DependencyApplyConfiguration {
	b.Name = &value
	return b
}
