// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/chrysopoeia/api/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DependencyGroupStatusApplyConfiguration represents a declarative configuration of the DependencyGroupStatus type for use
// with apply.
//
// DependencyGroupStatus defines the observed state of DependencyGroup.
type DependencyGroupStatusApplyConfiguration struct {
	// State is Accepted if the group holds the claim on all of its CRDs, and Rejected otherwise.
	// Only accepted groups may be referenced by a CustomResourceDefinitionSource.
	State *apiv1.DependencyGroupState `json:"state,omitempty"`
	// Conditions holds the conditions for the DependencyGroup. The Accepted condition carries the
	// reason a group was rejected.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DependencyGroupStatusApplyConfiguration constructs a declarative configuration of the DependencyGroupStatus type for use with
// apply.
func DependencyGroupStatus() *DependencyGroupStatusApplyConfiguration {
	return &DependencyGroupStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DependencyGroupStatusApplyConfiguration) WithState(value apiv1.DependencyGroupState) *DependencyGroupStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DependencyGroupStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DependencyGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
