// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/chrysopoeia/api/v1"
	internal "github.com/helmetica-framework/chrysopoeia/api/v1/applyconfiguration/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DependencyGroupApplyConfiguration represents a declarative configuration of the DependencyGroup type for use
// with apply.
//
// DependencyGroup is the Schema for the dependencygroups API.
// It bundles the CustomResourceDefinitions of a service so that charts can depend on the group
// instead of on individual CRDs, and ties them to the harness of the managing operator.
type DependencyGroupApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:""`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *DependencyGroupSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *DependencyGroupStatusApplyConfiguration `json:"status,omitempty"`
}

// DependencyGroup constructs a declarative configuration of the DependencyGroup type for use with
// apply.
func DependencyGroup(name string) *DependencyGroupApplyConfiguration {
	b := &DependencyGroupApplyConfiguration{}
	b.WithName(name)
	b.WithKind("DependencyGroup")
	b.WithAPIVersion("helmetica.io/v1")
	return b
}

// ExtractDependencyGroupFrom extracts the applied configuration owned by fieldManager from
// dependencyGroup for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// dependencyGroup must be a unmodified DependencyGroup API object that was retrieved from the Kubernetes API.
// ExtractDependencyGroupFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDependencyGroupFrom(dependencyGroup *apiv1.DependencyGroup, fieldManager string, subresource string) (*DependencyGroupApplyConfiguration, error) {
	b := &DependencyGroupApplyConfiguration{}
	err := managedfields.ExtractInto(dependencyGroup, internal.Parser().Type("com.github.helmetica-framework.chrysopoeia.api.v1.DependencyGroup"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(dependencyGroup.Name)

	b.WithKind("DependencyGroup")
	b.WithAPIVersion("helmetica.io/v1")
	return b, nil
}

// ExtractDependencyGroup extracts the applied configuration owned by fieldManager from
// dependencyGroup. If no managedFields are found in dependencyGroup for fieldManager, a
// DependencyGroupApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// dependencyGroup must be a unmodified DependencyGroup API object that was retrieved from the Kubernetes API.
// ExtractDependencyGroup provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDependencyGroup(dependencyGroup *apiv1.DependencyGroup, fieldManager string) (*DependencyGroupApplyConfiguration, error) {
	return ExtractDependencyGroupFrom(dependencyGroup, fieldManager, "")
}

// ExtractDependencyGroupStatus extracts the applied configuration owned by fieldManager from
// dependencyGroup for the status subresource.
func ExtractDependencyGroupStatus(dependencyGroup *apiv1.DependencyGroup, fieldManager string) (*DependencyGroupApplyConfiguration, error) {
	return ExtractDependencyGroupFrom(dependencyGroup, fieldManager, "status")
}

func (b DependencyGroupApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithKind(value string) *DependencyGroupApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithAPIVersion(value string) *DependencyGroupApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithName(value string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithGenerateName(value string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithNamespace(value string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithUID(value types.UID) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithResourceVersion(value string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithGeneration(value int64) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *DependencyGroupApplyConfiguration) WithLabels(entries map[string]string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *DependencyGroupApplyConfiguration) WithAnnotations(entries map[string]string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *DependencyGroupApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *DependencyGroupApplyConfiguration) WithFinalizers(values ...string) *DependencyGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *DependencyGroupApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithSpec(value *DependencyGroupSpecApplyConfiguration) *DependencyGroupApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DependencyGroupApplyConfiguration) WithStatus(value *DependencyGroupStatusApplyConfiguration) *DependencyGroupApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *DependencyGroupApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *DependencyGroupApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *DependencyGroupApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *DependencyGroupApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
