// Code generated by controller-gen. DO NOT EDIT.

package v1

// DependencyGroupReferenceApplyConfiguration represents a declarative configuration of the DependencyGroupReference type for use
// with apply.
//
// DependencyGroupReference references a DependencyGroup and names the scope it is used under.
type DependencyGroupReferenceApplyConfiguration struct {
	// Name of the DependencyGroup.
	Name *string `json:"name,omitempty"`
	// As overrides the name the scope label is built from, so that a second deployment of the same
	// operator can serve a separate set of consumers. Both the managing operator and its consumers
	// have to set the same alias to end up in the same scope.
	As *string `json:"as,omitempty"`
}

// DependencyGroupReferenceApplyConfiguration constructs a declarative configuration of the DependencyGroupReference type for use with
// apply.
func DependencyGroupReference() *DependencyGroupReferenceApplyConfiguration {
	return &DependencyGroupReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DependencyGroupReferenceApplyConfiguration) WithName(value string) *DependencyGroupReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithAs sets the As field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the As field is set to the value of the last call.
func (b *DependencyGroupReferenceApplyConfiguration) WithAs(value string) *DependencyGroupReferenceApplyConfiguration {
	b.As = &value
	return b
}
