// Code generated by controller-gen. DO NOT EDIT.

package v1

// DependencyGroupCRDApplyConfiguration represents a declarative configuration of the DependencyGroupCRD type for use
// with apply.
//
// DependencyGroupCRD identifies a CustomResourceDefinition belonging to a DependencyGroup.
type DependencyGroupCRDApplyConfiguration struct {
	// Name is the fully qualified name of the CRD, as written in its `.metadata.name`.
	Name *string `json:"name,omitempty"`
}

// DependencyGroupCRDApplyConfiguration constructs a declarative configuration of the DependencyGroupCRD type for use with
// apply.
func DependencyGroupCRD() *DependencyGroupCRDApplyConfiguration {
	return &DependencyGroupCRDApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DependencyGroupCRDApplyConfiguration) WithName(value string) *DependencyGroupCRDApplyConfiguration {
	b.Name = &value
	return b
}
