// Code generated by controller-gen. DO NOT EDIT.

package v1

// DependencyGroupSpecApplyConfiguration represents a declarative configuration of the DependencyGroupSpec type for use
// with apply.
//
// DependencyGroupSpec defines the desired state of DependencyGroup.
type DependencyGroupSpecApplyConfiguration struct {
	// CRDs are the CustomResourceDefinitions that belong to this group.
	// A CRD must not belong to more than one group, groups claiming an already claimed CRD are
	// rejected. The CRDs do not have to exist yet.
	CRDs []DependencyGroupCRDApplyConfiguration `json:"crds,omitempty"`
	// HarnessRef references the harness of the operator managing the CRDs of this group.
	HarnessRef *HarnessReferenceApplyConfiguration `json:"harnessRef,omitempty"`
}

// DependencyGroupSpecApplyConfiguration constructs a declarative configuration of the DependencyGroupSpec type for use with
// apply.
func DependencyGroupSpec() *DependencyGroupSpecApplyConfiguration {
	return &DependencyGroupSpecApplyConfiguration{}
}

// WithCRDs adds the given value to the CRDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CRDs field.
func (b *DependencyGroupSpecApplyConfiguration) WithCRDs(values ...*DependencyGroupCRDApplyConfiguration) *DependencyGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCRDs")
		}
		b.CRDs = append(b.CRDs, *values[i])
	}
	return b
}

// WithHarnessRef sets the HarnessRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HarnessRef field is set to the value of the last call.
func (b *DependencyGroupSpecApplyConfiguration) WithHarnessRef(value *HarnessReferenceApplyConfiguration) *DependencyGroupSpecApplyConfiguration {
	b.HarnessRef = value
	return b
}
