// Code generated by controller-gen. DO NOT EDIT.

package v1

// DependencyReferenceApplyConfiguration represents a declarative configuration of the DependencyReference type for use
// with apply.
//
// DependencyReference references a dependency. Exactly one referent has to be set.
type DependencyReferenceApplyConfiguration struct {
	// DependencyGroup references a DependencyGroup.
	DependencyGroup *DependencyGroupReferenceApplyConfiguration `json:"dependencyGroup,omitempty"`
}

// DependencyReferenceApplyConfiguration constructs a declarative configuration of the DependencyReference type for use with
// apply.
func DependencyReference() *DependencyReferenceApplyConfiguration {
	return &DependencyReferenceApplyConfiguration{}
}

// WithDependencyGroup sets the DependencyGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependencyGroup field is set to the value of the last call.
func (b *DependencyReferenceApplyConfiguration) WithDependencyGroup(value *DependencyGroupReferenceApplyConfiguration) *DependencyReferenceApplyConfiguration {
	b.DependencyGroup = value
	return b
}
