// Code generated by controller-gen. DO NOT EDIT.

package v1

// DiscoveryReferenceApplyConfiguration represents a declarative configuration of the DiscoveryReference type for use
// with apply.
type DiscoveryReferenceApplyConfiguration struct {
	// APIVersion of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind of the referent.
	Kind *string `json:"kind,omitempty"`
	// Name of the referent.
	Name *string `json:"name,omitempty"`
}

// DiscoveryReferenceApplyConfiguration constructs a declarative configuration of the DiscoveryReference type for use with
// apply.
func DiscoveryReference() *DiscoveryReferenceApplyConfiguration {
	return &DiscoveryReferenceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DiscoveryReferenceApplyConfiguration) WithAPIVersion(value string) *DiscoveryReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DiscoveryReferenceApplyConfiguration) WithKind(value string) *DiscoveryReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DiscoveryReferenceApplyConfiguration) WithName(value string) *DiscoveryReferenceApplyConfiguration {
	b.Name = &value
	return b
}
