// Code generated by controller-gen. DO NOT EDIT.

package v1

// HarnessReferenceApplyConfiguration represents a declarative configuration of the HarnessReference type for use
// with apply.
//
// HarnessReference references an OperatorHarness.
type HarnessReferenceApplyConfiguration struct {
	// Kind of the referent.
	Kind *string `json:"kind,omitempty"`
	// Name of the referent.
	Name *string `json:"name,omitempty"`
}

// HarnessReferenceApplyConfiguration constructs a declarative configuration of the HarnessReference type for use with
// apply.
func HarnessReference() *HarnessReferenceApplyConfiguration {
	return &HarnessReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *HarnessReferenceApplyConfiguration) WithKind(value string) *HarnessReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HarnessReferenceApplyConfiguration) WithName(value string) *HarnessReferenceApplyConfiguration {
	b.Name = &value
	return b
}
