// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InstanceRevisionSpecApplyConfiguration represents a declarative configuration of the InstanceRevisionSpec type for use
// with apply.
//
// InstanceRevisionSpec defines the desired state of InstanceRevision.
type InstanceRevisionSpecApplyConfiguration struct {
	// Version is the version of the Helm chart.
	Version *string `json:"version,omitempty"`
	// Values is the values of the Helm chart.
	Values *apiextensionsv1.JSON `json:"values,omitempty"`
	// OCIUrl is the OCI repository URL where the service bundle is stored.
	// TODO: This field will be changed/removed in the future to reference a Flux OCIRepository resource instead of a raw URL.
	OCIUrl *string `json:"ociUrl,omitempty"`
	// ApprovedAt is the timestamp when the revision was approved.
	// The newest approved revision is the one that will be used for deployment.
	// The revision
	ApprovedAt *metav1.Time `json:"approvedAt,omitempty"`
}

// InstanceRevisionSpecApplyConfiguration constructs a declarative configuration of the InstanceRevisionSpec type for use with
// apply.
func InstanceRevisionSpec() *InstanceRevisionSpecApplyConfiguration {
	return &InstanceRevisionSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *InstanceRevisionSpecApplyConfiguration) WithVersion(value string) *InstanceRevisionSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *InstanceRevisionSpecApplyConfiguration) WithValues(value apiextensionsv1.JSON) *InstanceRevisionSpecApplyConfiguration {
	b.Values = &value
	return b
}

// WithOCIUrl sets the OCIUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OCIUrl field is set to the value of the last call.
func (b *InstanceRevisionSpecApplyConfiguration) WithOCIUrl(value string) *InstanceRevisionSpecApplyConfiguration {
	b.OCIUrl = &value
	return b
}

// WithApprovedAt sets the ApprovedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovedAt field is set to the value of the last call.
func (b *InstanceRevisionSpecApplyConfiguration) WithApprovedAt(value metav1.Time) *InstanceRevisionSpecApplyConfiguration {
	b.ApprovedAt = &value
	return b
}
