// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/chrysopoeia/api/v1"
	internal "github.com/helmetica-framework/chrysopoeia/api/v1/applyconfiguration/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// OperatorHarnessApplyConfiguration represents a declarative configuration of the OperatorHarness type for use
// with apply.
//
// OperatorHarness is the Schema for the operatorharnesses API.
// It harnesses an operator that would otherwise require cluster-wide permissions by scoping its
// access to resources carrying the label in `.spec.scopeToLabel`.
type OperatorHarnessApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:""`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *OperatorHarnessSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *OperatorHarnessStatusApplyConfiguration `json:"status,omitempty"`
}

// OperatorHarness constructs a declarative configuration of the OperatorHarness type for use with
// apply.
func OperatorHarness(name string) *OperatorHarnessApplyConfiguration {
	b := &OperatorHarnessApplyConfiguration{}
	b.WithName(name)
	b.WithKind("OperatorHarness")
	b.WithAPIVersion("helmetica.io/v1")
	return b
}

// ExtractOperatorHarnessFrom extracts the applied configuration owned by fieldManager from
// operatorHarness for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// operatorHarness must be a unmodified OperatorHarness API object that was retrieved from the Kubernetes API.
// ExtractOperatorHarnessFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractOperatorHarnessFrom(operatorHarness *apiv1.OperatorHarness, fieldManager string, subresource string) (*OperatorHarnessApplyConfiguration, error) {
	b := &OperatorHarnessApplyConfiguration{}
	err := managedfields.ExtractInto(operatorHarness, internal.Parser().Type("com.github.helmetica-framework.chrysopoeia.api.v1.OperatorHarness"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(operatorHarness.Name)

	b.WithKind("OperatorHarness")
	b.WithAPIVersion("helmetica.io/v1")
	return b, nil
}

// ExtractOperatorHarness extracts the applied configuration owned by fieldManager from
// operatorHarness. If no managedFields are found in operatorHarness for fieldManager, a
// OperatorHarnessApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// operatorHarness must be a unmodified OperatorHarness API object that was retrieved from the Kubernetes API.
// ExtractOperatorHarness provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractOperatorHarness(operatorHarness *apiv1.OperatorHarness, fieldManager string) (*OperatorHarnessApplyConfiguration, error) {
	return ExtractOperatorHarnessFrom(operatorHarness, fieldManager, "")
}

// ExtractOperatorHarnessStatus extracts the applied configuration owned by fieldManager from
// operatorHarness for the status subresource.
func ExtractOperatorHarnessStatus(operatorHarness *apiv1.OperatorHarness, fieldManager string) (*OperatorHarnessApplyConfiguration, error) {
	return ExtractOperatorHarnessFrom(operatorHarness, fieldManager, "status")
}

func (b OperatorHarnessApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithKind(value string) *OperatorHarnessApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithAPIVersion(value string) *OperatorHarnessApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithName(value string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithGenerateName(value string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithNamespace(value string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithUID(value types.UID) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithResourceVersion(value string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithGeneration(value int64) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *OperatorHarnessApplyConfiguration) WithLabels(entries map[string]string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *OperatorHarnessApplyConfiguration) WithAnnotations(entries map[string]string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *OperatorHarnessApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *OperatorHarnessApplyConfiguration) WithFinalizers(values ...string) *OperatorHarnessApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *OperatorHarnessApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithSpec(value *OperatorHarnessSpecApplyConfiguration) *OperatorHarnessApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *OperatorHarnessApplyConfiguration) WithStatus(value *OperatorHarnessStatusApplyConfiguration) *OperatorHarnessApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *OperatorHarnessApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *OperatorHarnessApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *OperatorHarnessApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *OperatorHarnessApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
