// Code generated by controller-gen. DO NOT EDIT.

package v1

// OperatorHarnessOperatorApplyConfiguration represents a declarative configuration of the OperatorHarnessOperator type for use
// with apply.
//
// OperatorHarnessOperator describes where the harnessed operator runs and how it is harnessed.
type OperatorHarnessOperatorApplyConfiguration struct {
	// Namespace is the namespace the harnessed operator runs in.
	Namespace *string `json:"namespace,omitempty"`
	// ServiceAccounts are the service accounts, in Namespace, the harnessed operator's pods run as.
	// Only pods running as one of these service accounts are harnessed. If empty, every pod in
	// Namespace is harnessed, which is what a namespace holding a single operator wants: the service
	// account is named by the operator's chart and does not have to be known up front.
	ServiceAccounts []string `json:"serviceAccounts,omitempty"`
	// InjectProxyConfiguration defines if the harnessed operator should have the harness proxy injected.
	// If enabled, the harness copies the proxy's CA certificate to Namespace and registers a mutating
	// webhook that points the operator's pods at the harness proxy instead of the Kubernetes API server.
	InjectProxyConfiguration *bool `json:"injectProxyConfiguration,omitempty"`
}

// OperatorHarnessOperatorApplyConfiguration constructs a declarative configuration of the OperatorHarnessOperator type for use with
// apply.
func OperatorHarnessOperator() *OperatorHarnessOperatorApplyConfiguration {
	return &OperatorHarnessOperatorApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *OperatorHarnessOperatorApplyConfiguration) WithNamespace(value string) *OperatorHarnessOperatorApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithServiceAccounts adds the given value to the ServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServiceAccounts field.
func (b *OperatorHarnessOperatorApplyConfiguration) WithServiceAccounts(values ...string) *OperatorHarnessOperatorApplyConfiguration {
	for i := range values {
		b.ServiceAccounts = append(b.ServiceAccounts, values[i])
	}
	return b
}

// WithInjectProxyConfiguration sets the InjectProxyConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InjectProxyConfiguration field is set to the value of the last call.
func (b *OperatorHarnessOperatorApplyConfiguration) WithInjectProxyConfiguration(value bool) *OperatorHarnessOperatorApplyConfiguration {
	b.InjectProxyConfiguration = &value
	return b
}
