// Code generated by controller-gen. DO NOT EDIT.

package v1

// OperatorHarnessSpecApplyConfiguration represents a declarative configuration of the OperatorHarnessSpec type for use
// with apply.
//
// OperatorHarnessSpec defines the desired state of OperatorHarness.
type OperatorHarnessSpecApplyConfiguration struct {
	// ScopeToLabel is the label that needs to be present on a resource for the harnessed operator to manage it.
	// It is used to scope cluster-wide permissions: if the harnessed operator does a cluster-scoped list or
	// watch through the harness proxy, it only sees resources carrying this label.
	ScopeToLabel *string `json:"scopeToLabel,omitempty"`
	// Operator describes the harnessed operator's workload.
	Operator *OperatorHarnessOperatorApplyConfiguration `json:"operator,omitempty"`
}

// OperatorHarnessSpecApplyConfiguration constructs a declarative configuration of the OperatorHarnessSpec type for use with
// apply.
func OperatorHarnessSpec() *OperatorHarnessSpecApplyConfiguration {
	return &OperatorHarnessSpecApplyConfiguration{}
}

// WithScopeToLabel sets the ScopeToLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScopeToLabel field is set to the value of the last call.
func (b *OperatorHarnessSpecApplyConfiguration) WithScopeToLabel(value string) *OperatorHarnessSpecApplyConfiguration {
	b.ScopeToLabel = &value
	return b
}

// WithOperator sets the Operator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Operator field is set to the value of the last call.
func (b *OperatorHarnessSpecApplyConfiguration) WithOperator(value *OperatorHarnessOperatorApplyConfiguration) *OperatorHarnessSpecApplyConfiguration {
	b.Operator = value
	return b
}
