// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// OperatorHarnessStatusApplyConfiguration represents a declarative configuration of the OperatorHarnessStatus type for use
// with apply.
//
// OperatorHarnessStatus defines the observed state of OperatorHarness.
type OperatorHarnessStatusApplyConfiguration struct {
	// Conditions holds the conditions for the OperatorHarness.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// OperatorHarnessStatusApplyConfiguration constructs a declarative configuration of the OperatorHarnessStatus type for use with
// apply.
func OperatorHarnessStatus() *OperatorHarnessStatusApplyConfiguration {
	return &OperatorHarnessStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OperatorHarnessStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *OperatorHarnessStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
