// Code generated by controller-gen. DO NOT EDIT.

package v1

// SourceReferenceApplyConfiguration represents a declarative configuration of the SourceReference type for use
// with apply.
type SourceReferenceApplyConfiguration struct {
	// APIVersion of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind of the referent.
	Kind *string `json:"kind,omitempty"`
	// Name of the referent.
	Name *string `json:"name,omitempty"`
}

// SourceReferenceApplyConfiguration constructs a declarative configuration of the SourceReference type for use with
// apply.
func SourceReference() *SourceReferenceApplyConfiguration {
	return &SourceReferenceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithAPIVersion(value string) *SourceReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithKind(value string) *SourceReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithName(value string) *SourceReferenceApplyConfiguration {
	b.Name = &value
	return b
}
