// Code generated by controller-gen. DO NOT EDIT.

package v1

// VersionDiscoveryApplyConfiguration represents a declarative configuration of the VersionDiscovery type for use
// with apply.
type VersionDiscoveryApplyConfiguration struct {
	// Reference is a reference to the discovery source of the version.
	Reference *DiscoveryReferenceApplyConfiguration `json:"reference,omitempty"`
}

// VersionDiscoveryApplyConfiguration constructs a declarative configuration of the VersionDiscovery type for use with
// apply.
func VersionDiscovery() *VersionDiscoveryApplyConfiguration {
	return &VersionDiscoveryApplyConfiguration{}
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *VersionDiscoveryApplyConfiguration) WithReference(value *DiscoveryReferenceApplyConfiguration) *VersionDiscoveryApplyConfiguration {
	b.Reference = value
	return b
}
