// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/helmetica-framework/chrysopoeia/api/v1"
	apiv1 "github.com/helmetica-framework/chrysopoeia/api/v1/applyconfiguration/api/v1"
	internal "github.com/helmetica-framework/chrysopoeia/api/v1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=helmetica.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("CustomResourceDefinitionSource"):
		return &apiv1.CustomResourceDefinitionSourceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CustomResourceDefinitionSourceSpec"):
		return &apiv1.CustomResourceDefinitionSourceSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CustomResourceDefinitionSourceStatus"):
		return &apiv1.CustomResourceDefinitionSourceStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DiscoveryReference"):
		return &apiv1.DiscoveryReferenceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("InstanceRevision"):
		return &apiv1.InstanceRevisionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("InstanceRevisionSpec"):
		return &apiv1.InstanceRevisionSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SourceReference"):
		return &apiv1.SourceReferenceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("VersionDiscovery"):
		return &apiv1.VersionDiscoveryApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
