
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chrysopoeia-flux-system
resources:
- https://github.com/fluxcd/source-controller//config/crd
- https://github.com/fluxcd/source-controller//config/rbac
- https://github.com/fluxcd/source-controller//config/manager
- https://github.com/fluxcd/image-reflector-controller//config/crd
- https://github.com/fluxcd/image-reflector-controller//config/rbac
- https://github.com/fluxcd/image-reflector-controller//config/manager
- https://github.com/fluxcd/helm-controller//config/crd
- https://github.com/fluxcd/helm-controller//config/rbac
- https://github.com/fluxcd/helm-controller//config/manager
- tag-serve-nginx-conf.yaml
- tags-serve-service.yaml
- namespace.yaml
patches:
- path: image_reflector_serve_tags_patch.yaml
